---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: csd_development
  :username: root
  :password: 
  :host: localhost
 # :socket: /tmp/mysql.sock
  :encoding: utf8

:test:
  <<: *defaults
  :database: csd_test

:production:
  <<: *defaults
  :database: csd_production
