---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: sqlite3
  :database: db/csd_development

:test:
  <<: *defaults
  :database: csd_test

:production:
  <<: *defaults
  :database: csd_production
