---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: schoolapp_development
  :username: root
  :password: 
  :encoding: utf8

:test:
  <<: *defaults
  :database: schoolapp_test

:production:
  <<: *defaults
  :database: schoolapp_production
  
:rake:
  <<: *defaults
  :database: schoolapp_development