dependency "merb-assets"
dependency "merb-cache"
dependency "merb-helpers"
dependency "merb-mailer"
dependency "merb-slices"
dependency "merb-auth"
dependency "merb-param-protection"
dependency "merb-auth-core"
dependency "merb-auth-more"
dependency "merb_has_flash"
dependency "fastercsv"
dependency "will_paginate", '3.0.0'
dependency "httparty"
##dependency "pdf-writer"

